name: Rank

on: [ push ]


jobs:
  rank:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout GoBiggerSubmit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: YangWuuu/GoBiggerSubmit
          path: './GoBiggerSubmit'

      - name: ls
        run: |
          ls -alh
          ls -alh GoBiggerSubmit

#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pylint