name: Rank

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  rank:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Checkout Self
        uses: actions/checkout@v2

      - name: Checkout GoBiggerSubmit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: YangWuuu/GoBiggerSubmit
          path: './GoBiggerSubmit'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Pip
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('GoBiggerSubmit/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Pip Install
        # if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r GoBiggerSubmit/requirements.txt

      - name: Cache rank.tmp
        uses: actions/cache@v2
        with:
          path: rank.tmp
          key: ${{ runner.os }}-rank-tmp

      - name: Run Battle
        run: |
          python3 battle.py --each-battle-size 30 --battle-count 1 --max-workers 4 --save-result README.md-bak

      - name: Save Result
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git stash
          git pull --rebase
          git stash apply stash@{0}
          mv README.md-bak README.md
          git add .
          git commit -m "auto upload"
          git push
