name: Rank

on: [ push ]


jobs:
  rank:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout GoBiggerSubmit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: YangWuuu/GoBiggerSubmit
          path: './GoBiggerSubmit'

#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('GoBiggerSubmit/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r GoBiggerSubmit/requirements.txt

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pylint