name: Rank

on: [ push ]


jobs:
  rank:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Self
        uses: actions/checkout@v2

      - name: Checkout GoBiggerSubmit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: YangWuuu/GoBiggerSubmit
          path: './GoBiggerSubmit'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name : Cache Pip
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('GoBiggerSubmit/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Pip Install
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r GoBiggerSubmit/requirements.txt

      - run: |
          python3 battle --each-battle-size 10 -battle-count 1 --max-workers 2
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto upload"
          git push
